# Generated by Django 4.1.7 on 2023-04-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_order_address_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
